export enum ChainEnum {
  CHAIN_NOT_EXISTS="CHAIN_NOT_EXISTS" ,
  ARCH_NOT_EXISTS="ARCH_NOT_EXISTS" ,
  CRYPTO_NOT_EXISTS="CRYPTO_NOT_EXISTS" ,
  EXCHANGE_NOT_EXISTS="EXCHANGE_NOT_EXISTS" ,
  EXCHANGE_VER_NOT_EXISTS="EXCHANGE_VER_NOT_EXISTS" ,
  TRANSACTION_FAILED="TRANSACTION_FAILED" ,
  BALANCE_IS_NOT_SUFFICIENT="BALANCE_IS_NOT_SUFFICIENT" ,


}