export enum CountryEnum {
  COUNTRY_NOT_EXISTS="COUNTRY_NOT_EXISTS" ,
  COUNTRY_NAME_ALREADY_EXISTS="COUNTRY_NAME_ALREADY_EXISTS" ,
  COUNTRY_ISO2_ALREADY_EXISTS="COUNTRY_ISO2_ALREADY_EXISTS" ,
  COUNTRY_ISO3_ALREADY_EXISTS="COUNTRY_ISO3_ALREADY_EXISTS" ,
  COUNTRY_RELATION_CURRENCY_NOT_EXISTS = "COUNTRY_RELATION_CURRENCY_NOT_EXISTS"
}