export enum CurrencyEnum {
  CURRENCY_NOT_EXISTS="CURRENCY_NOT_EXISTS" ,
  CURRENCY_NAME_ALREADY_EXISTS="CURRENCY_NAME_ALREADY_EXISTS" ,
  CURRENCY_CODE_ALREADY_EXISTS="CURRENCY_CODE_ALREADY_EXISTS" ,
  BANK_NOT_EXISTS="BANK_NOT_EXISTS" ,
  BANK_ALREADY_EXISTS="BANK_ALREADY_EXISTS" ,
  BANK_ALREADY_EXISTS_IN_CURRENCY="BANK_ALREADY_EXISTS_IN_CURRENCY" ,

}