export enum IpgEnum {
  IPG_NOT_EXISTS="IPG_NOT_EXISTS" ,
  IPG_NAME_ALREADY_EXISTS="IPG_NAME_ALREADY_EXISTS" ,
  IPG_HAS_ERROR_GET_LINK="IPG_HAS_ERROR_GET_LINK" ,
  IPG_ORDER_NOT_EXISTS="IPG_ORDER_NOT_EXISTS" ,
  WALLET_CURRENCY_OF_USER_NOT_MATCHED_IPG = "WALLET_CURRENCY_OF_USER_NOT_MATCHED_IPG" ,
  IPG_ALREADY_EXISTS_IN_COUNTRY_CURRENCY = "IPG_ALREADY_EXISTS_IN_COUNTRY_CURRENCY"
}