export enum PhoneEnum {
  PHONE_NUMBER_DENY_COUNTRY="PHONE_NUMBER_DENY_COUNTRY" ,
  PHONE_NUMBER_IS_NOT_EXISTS="PHONE_NUMBER_IS_NOT_EXISTS" ,
  PHONE_NUMBER_ALREADY_EXISTS="PHONE_NUMBER_ALREADY_EXISTS" ,


}