export enum PublicEnum {
  UUID_NOT_MATCH="UUID_NOT_MATCH" ,
  PUBLIC_ERROR="PUBLIC_ERROR" ,
  LANGUAGE_CODE_NOT_MATCH = "LANGUAGE_CODE_NOT_MATCH" ,
  LANGUAGE_INCOMPLETE = "LANGUAGE_INCOMPLETE" ,
  PHONE_NUMBER_IS_NOT_VALID = "LANGUAGE_INCOMPLETE" ,
  PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS" ,
  ACCESS_IS_DENIDE = "ACCESS_IS_DENIDE" ,
  USER_NOT_EXISTS = "USER_NOT_EXISTS" ,
  COLUMN_NOT_EXISTS="COLUMN_NOT_EXISTS" ,

}